<div class="wrap">
    <div class="settings-wrapper">
        <form id="form" class="flex-column">
            <div id="wrapper-status" class="action-select-wrap">
                <input id="input-status" type="hidden" name="status" value="<?php echo $block->getData('current-status-row')['status'] ?>"/>
                <button class="status-text action-select" title="Select Items">
                    <span id="input-status-text"><?php echo $block->getData('current-status-row')['label'] ?></span>
                </button>
                <div class="action-menu-items">
                    <ul id="list-status" class="action-menu">
                        <li onclick="handleDropdownOptionClick('', 'All')">
                            <span class="action-menu-item">All</span>
                        </li>
                        <?php foreach ($block->getData('statuses') as $status): ?>
                            <li onclick="handleDropdownOptionClick(<?php echo "'" . $status['status'] . "', '" . $status['label'] . "'" ?>)">
                                <span class="action-menu-item"><?php echo $status['label'] ?></span>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </div>
            </div>
            <div class="flex-ended">
                <div class="flex-centered flex-column">
                    <label for="input-date-from">From:</label>
                    <input type="text" id="input-date-from" class="input" placeholder="Date"
                           value="<?php echo ($block->getData('date-from')) ? $block->getData('date-from') : "" ?>">
                </div>
                <div class="wrapper-to-date flex-centered flex-column">
                    <label for="input-date-to">To:</label>
                    <input type="text" id="input-date-to" class="input" placeholder="Date"
                           value="<?php echo ($block->getData('date-to')) ? $block->getData('date-to') : "" ?>">
                </div>
                <button id="submit" title="Search for FireAds orders" type="submit" class="action-default scalable save primary save-encryption-key ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" data-ui-id="crypt-key-edit-save-button" role="button" aria-disabled="false">
                    <span class="ui-button-text">
                        <span>Submit</span>
                    </span>
                </button>
            </div>
        </form>
        <div class="tablenav-pages">
            <span class="displaying-num"><?php echo $block->getData('searched-orders-count') ?> positions</span>
            <span class="pagination-links">
                <?php if ($block->getData('current-page') > 1): ?>
                    <button id="btn-page-first" class="next-page button-date">
                        <span aria-hidden="true">«</span>
                    </button>
                    <button id="btn-page-previous" class="last-page button-date">
                        <span aria-hidden="true">‹</span>
                    </button>
                <?php else: ?>
                    <span class="tablenav-pages-navspan button-date disabled" aria-hidden="true">«</span>
                    <span class="tablenav-pages-navspan button-date disabled" aria-hidden="true">‹</span>
                <?php endif; ?>
                <span class="paging-input">
                    <input class="button-date" id="current-page-input" type="text" name="paged"
                           value="<?php echo $block->getData('current-page') ?>" size="1" aria-describedby="table-paging">
                    <span class="tablenav-paging-text">
                        out of
                        <span id="pages-count" class="total-pages"><?php echo $block->getData('pages-count'); ?></span>
                    </span>
                 </span>
                <?php if ($block->getData('current-page') < $block->getData('pages-count')): ?>
                    <button id="btn-page-next" class="next-page button-date">
                        <span aria-hidden="true">›</span>
                    </button>
                    <button id="btn-page-last" class="last-page button-date">
                        <span aria-hidden="true">»</span>
                    </button>
                <?php else: ?>
                    <span class="tablenav-pages-navspan button-date disabled" aria-hidden="true">›</span>
                    <span class="tablenav-pages-navspan button-date disabled" aria-hidden="true">»</span>
                <?php endif; ?>
            </span>
        </div>
    </div>
    <table class="data-grid data-grid-draggable" data-role="grid">
        <thead>
        <tr>
            <th class="data-grid-th _sortable _draggable">
                <span class="data-grid-cell-content">Order</span>
            </th>
            <th class="data-grid-th _sortable _draggable">
                <span class="data-grid-cell-content">Date</span>
            </th>
            <th class="data-grid-th _sortable _draggable">
                <span class="data-grid-cell-content">Total</span>
            </th>
        </thead>
        <tbody>
        <?php foreach ($block->getData('page-orders') as $order): ?>
            <tr class="data-row" data-repeat-index="0">
                <td class="">
                    <div class="data-grid-cell-content">#<?php echo $order['entity_id'] ?></div>
                </td>
                <td class="">
                    <div class="data-grid-cell-content"><?php echo $order['created_at'] ?></div>
                </td>
                <td class="">
                    <div class="data-grid-cell-content"><?php echo round($order['grand_total'], 2) . ' ' . $order['base_currency_code'] ?></div>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    requirejs(['flatpickr'], function() {
        requirejs(['orders']);
    })
</script>
